# Generated by Django 4.2.2 on 2023-06-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_task_taskdesc_alter_task_tasktitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
