# Generated by Django 4.2.2 on 2023-06-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_task_taskdesc_alter_task_tasktitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskStatus',
            field=models.IntegerField(default=0),
        ),
    ]
