# Generated by Django 4.2.2 on 2023-07-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_task_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(default='swapnil', max_length=100),
            preserve_default=False,
        ),
    ]
