# Generated by Django 4.2.2 on 2023-07-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_task_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='username',
            new_name='userName',
        ),
    ]
